name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup and execute Linux
        if: runner.os == 'Linux'
        run: |
          chmod +x scripts/setup_linux.sh
          ./scripts/setup_linux.sh

      - name: Setup and execute macOS
        if: runner.os == 'macOS'
        run: |
          chmod +x scripts/setup_macos.sh
          ./scripts/setup_macos.sh